### ISSUE TITLE
關於時區錯亂

### ISSUE THREAD

**Issue by ayhaadam** [allPay/allPayPHPCartModule#3]
Code 裡面用到了幾個 php date()，例如丟給歐付寶 API 產生訂單時會丟一個訂單產生時間，但因為在 Wordpress 裡面會無視主機時區，預設使用 GMT 時間（Wordpress 跟自有伺服器通聯的特殊需求）而不是台灣的 +8 時區，所以時間都會晚八小時。應該使用 Wordpress [current_time()](https://developer.wordpress.org/reference/functions/current_time/) 取代之。

**Comment by AllennChang** [comment]
感謝你提供寶貴的意見,我們已反應給開發小組,
