### ISSUE TITLE
Checking out at step 6, show empty 

### ISSUE THREAD

**Issue by SwellShine** [allPay/allPayPHPCartModule#5]
2.1.0.1 with Ship2Pay module,

Allpay module install done, At step 6(Confirm order) of check out, nothing show.

http://imgur.com/a/CIZRR

**Comment by akilachen** [comment]
本版本已經支援opencart 2.3.0.2了嗎？

**Comment by AllennChang** [comment]
目前尚未支援, 我們已安排在做調整,未來的版本會支援opencart 2.3.0.2
